# -*- coding: utf-8 -*-
"""app_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xXd2ZNCx9D-rnM4o9IqhlNgP-ShQhpS
"""

import streamlit as st
from pathlib import Path

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Amrutha P | Data Scientist & AI",
    page_icon="💻",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# ---------------- CUSTOM CSS ----------------
st.markdown("""
<style>

html {
    scroll-behavior: smooth;
}

body {
    font-family: Arial, sans-serif;
}

.block-container {
    padding-top: 2rem;
    padding-bottom: 2rem;
    max-width: 1200px;
}

/* Hero */
.hero {
    text-align: center;
    padding: 70px 20px 50px 20px;
}

.hero h1 {
    font-size: 55px;
    margin-bottom: 10px;
    font-weight: 700;
}

.hero h2 {
    font-size: 25px;
    font-weight: 400;
    margin-bottom: 20px;
}

.hero p {
    font-size: 20px;
    max-width: 800px;
    margin: auto;
    line-height: 1.6;
}

/* Section */
.section-title {
    font-size: 35px;
    font-weight: 700;
    margin-top: 50px;
    margin-bottom: 25px;
}

/* Cards */
.card {
    padding: 25px;
    border-radius: 15px;
    border: 1px solid #ddd;
    margin-bottom: 20px;
    height: 100%;
}

.card h3 {
    font-size: 23px;
}

.card p {
    line-height: 1.6;
}

.skill {
    display: inline-block;
    padding: 8px 14px;
    margin: 5px;
    border-radius: 20px;
    border: 1px solid #ccc;
    font-size: 14px;
}

/* Buttons */
.button {
    display: inline-block;
    padding: 12px 22px;
    margin: 8px;
    border-radius: 8px;
    border: 1px solid #888;
    text-decoration: none;
    font-weight: 600;
}

/* Footer */
.footer {
    text-align: center;
    padding: 40px 10px;
    margin-top: 60px;
    border-top: 1px solid #ddd;
}

</style>
""", unsafe_allow_html=True)


# ---------------- HERO ----------------

st.markdown("""
<div class="hero">

<h1>Amrutha P</h1>

<h2>Data Scientist • Machine Learning • Artificial Intelligence</h2>

<p>
Turning Data Into Actionable Insights
</p>

<p>
Passionate about data analysis, machine learning,
artificial intelligence and building practical solutions
to real-world problems.
</p>

<a class="button"
href="https://github.com/Amrutha-DataScientist"
target="_blank">
GitHub
</a>

<a class="button"
href="https://www.linkedin.com/in/amrutha-preyala"
target="_blank">
LinkedIn
</a>

<a class="button"
href="mailto:amruthapreyala@gmail.com">
Email Me
</a>

</div>
""", unsafe_allow_html=True)


# ---------------- ABOUT ----------------

st.markdown(
    '<div class="section-title">About Me</div>',
    unsafe_allow_html=True
)

st.write("""
I am an entry-level Data Scientist with a strong foundation in
Python, SQL, statistics, machine learning and artificial intelligence.

I enjoy working with data through data cleaning, exploratory data analysis,
data visualization, feature engineering, feature selection and predictive
modeling.

My learning and project experience also includes deep learning, NLP,
Generative AI, LLMs, Transformers, RAG and chatbot development.

I focus on using data and AI techniques to solve practical problems
and generate meaningful insights.
""")


# ---------------- SKILLS ----------------

st.markdown(
    '<div class="section-title">Technical Skills</div>',
    unsafe_allow_html=True
)

skills = [
    "Python",
    "SQL",
    "MSSQL",
    "NumPy",
    "Pandas",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "Power BI",
    "Excel",
    "Data Cleaning",
    "EDA",
    "Data Visualization",
    "Feature Engineering",
    "Feature Selection",
    "Feature Mapping",
    "Machine Learning",
    "ML Algorithms",
    "Linear Regression",
    "Logistic Regression",
    "Decision Tree",
    "Random Forest",
    "XGBoost",
    "KNN",
    "K-Means",
    "Bagging",
    "Boosting",
    "AdaBoost",
    "PCA",
    "Dimensionality Reduction",
    "Time Series",
    "ARIMA",
    "Deep Learning",
    "Neural Networks",
    "CNN",
    "RNN",
    "LSTM",
    "NLP",
    "Generative AI",
    "LLMs",
    "Transformers",
    "Hugging Face",
    "RAG",
    "LangChain",
    "Chatbots",
    "Scikit-learn",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "Streamlit"
]

skill_html = ""

for skill in skills:
    skill_html += f'<span class="skill">{skill}</span>'

st.markdown(skill_html, unsafe_allow_html=True)


# ---------------- PROJECTS ----------------

st.markdown(
    '<div class="section-title">Projects</div>',
    unsafe_allow_html=True
)

projects = [

    {
        "title": "Netflix Movie Recommendation System",
        "description": """
        Built a recommendation system to recommend movies based on
        user ratings and movie information. Applied collaborative
        filtering concepts and Singular Value Decomposition (SVD)
        for recommendation.
        """,
        "github": "https://github.com/Amrutha-DataScientist/reccomendation_system"
    },

    {
        "title": "Air Passenger Demand Forecasting",
        "description": """
        Developed a time-series forecasting model to analyze and
        predict passenger demand. Used ARIMA-based forecasting to
        identify trends and future demand patterns.
        """,
        "github": "https://github.com/Amrutha-DataScientist/airpassengers-time-series-forecasting"
    },

    {
        "title": "Customer Churn Prediction",
        "description": """
        Developed a machine learning model to predict customer churn.
        Applied data preprocessing, feature selection, scaling,
        RFE and SMOTE to improve model performance and identify
        customers requiring retention strategies.
        """,
        "github": "https://github.com/Amrutha-DataScientist/Cutstomer-Churn"
    },

    {
        "title": "Customer Segmentation using K-Means",
        "description": """
        Performed customer segmentation using K-Means clustering.
        Analyzed customer spending and purchasing behavior to identify
        meaningful customer groups for business insights.
        """,
        "github": "https://github.com/Amrutha-DataScientist/customer_segmentation"
    },

    {
        "title": "LLM-Based AI Chatbot",
        "description": """
        Developed an AI chatbot using Generative AI concepts,
        LangChain, LLMs and prompt engineering. Explored retrieval
        augmented generation and conversational AI techniques.
        """
    }
]


for i in range(0, len(projects), 2):

    cols = st.columns(2)

    for j, col in enumerate(cols):

        index = i + j

        if index < len(projects):

            project = projects[index]

            with col:

                st.markdown(
                    f"""
                    <div class="card">

                    <h3>{project["title"]}</h3>

                    <p>
                    {project["description"]}
                    </p>

                    """,
                    unsafe_allow_html=True
                )

                if "github" in project:

                    st.markdown(
                        f"""
                        <a class="button"
                        href="{project["github"]}"
                        target="_blank">
                        View on GitHub →
                        </a>
                        </div>
                        """,
                        unsafe_allow_html=True
                    )

                else:

                    st.markdown(
                        "</div>",
                        unsafe_allow_html=True
                    )


# ---------------- TRAINING ----------------

st.markdown(
    '<div class="section-title">Training</div>',
    unsafe_allow_html=True
)

st.markdown("""
<div class="card">

<h3>Advanced Certification in Data Science & AI</h3>

<p>
Intellipaat in collaboration with iHUB DivyaSampark, IIT Roorkee
</p>

<p>
Training areas include Python, SQL, Statistics, Machine Learning,
Deep Learning, NLP, Generative AI and Artificial Intelligence.
</p>

</div>
""", unsafe_allow_html=True)


# ---------------- EDUCATION ----------------

st.markdown(
    '<div class="section-title">Education</div>',
    unsafe_allow_html=True
)

education = [
    (
        "B.Tech – Computer Science & Engineering",
        "Ravindra College of Engineering for Women",
        "2021 – 2025 | 75%"
    ),
    (
        "Intermediate – MPC",
        "Narayana Junior College for Women",
        "2021 | 75.6%"
    ),
    (
        "SSC",
        "Sri Lakshmi High School",
        "2019 | 9.0 GPA"
    )
]

for degree, college, year in education:

    st.markdown(
        f"""
        <div class="card">

        <h3>{degree}</h3>

        <p>{college}</p>

        <p><strong>{year}</strong></p>

        </div>
        """,
        unsafe_allow_html=True
    )


# ---------------- CERTIFICATIONS ----------------

st.markdown(
    '<div class="section-title">Certification</div>',
    unsafe_allow_html=True
)

st.markdown("""
<div class="card">

<h3>Python with Data Science + SQL + AI</h3>

<p>
Intellipaat
</p>

</div>
""", unsafe_allow_html=True)


# ---------------- CONTACT ----------------

st.markdown(
    '<div class="section-title">Contact</div>',
    unsafe_allow_html=True
)

st.markdown("""
<div class="card">

<h3>Let's Connect</h3>

<p>
📧 Email:
<a href="mailto:amruthapreyala@gmail.com">
amruthapreyala@gmail.com
</a>
</p>

<p>
📍 Andhra Pradesh, India
</p>

<p>
Open to Data Scientist, Data Analyst, ML Engineer and AI opportunities.
</p>

<a class="button"
href="https://github.com/Amrutha-DataScientist"
target="_blank">
GitHub
</a>

<a class="button"
href="https://www.linkedin.com/in/amrutha-preyala"
target="_blank">
LinkedIn
</a>

</div>
""", unsafe_allow_html=True)


# ---------------- FOOTER ----------------

st.markdown("""
<div class="footer">

<p>© 2026 Amrutha P | Data Scientist & AI</p>

<p>
Built with Python & Streamlit
</p>

</div>
""", unsafe_allow_html=True)

!pip install streamlit